name: sabueso
description: Rastreador Bluetooth BLE multiplataforma con Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Bluetooth (La versión 2.0.2 no es estándar aún, usamos la última estable probada)
  flutter_blue_plus: ^2.0.2
  
  # Permisos
  permission_handler: ^12.0.1
  
  # Ubicación
  geolocator: ^14.0.2
  location: ^8.0.1
  
  # Almacenamiento local
  shared_preferences: ^2.3.2
  
  # Firebase
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  
  # Utilidades
  json_annotation: ^4.9.0
  vibration: ^3.1.4
  flutter_tts: ^4.0.2
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.0
  
  # ESTA es la clave para que funcione tu código
  flutter_foreground_task: ^9.1.0