name: sabueso
description: Rastreador Bluetooth BLE multiplataforma
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # === Integración de Firebase y Clima ===
  firebase_core: ^2.27.0        # Core de Firebase
  cloud_firestore: ^4.15.0      # ⭐ NUEVO: Para guardar en la nube
  http: ^1.2.1                   # Para la petición a la API del clima
  geocoding: ^3.0.0              # Para obtener el nombre de la ubicación
  # ======================================
  
  flutter_blue_plus: ^1.36.8
  permission_handler: ^11.4.0
  geolocator: ^10.1.1
  location: ^5.0.3
  shared_preferences: ^2.2.2
  json_annotation: ^4.8.1
  vibration: ^2.0.0
  flutter_tts: ^4.0.2
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.2
  flutter_foreground_task: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true