name: sabueso
description: Rastreador Bluetooth BLE multiplataforma con Firebase
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Bluetooth
  flutter_blue_plus: ^2.0.2
  
  # Permisos
  permission_handler: ^12.0.1
  
  # UbicaciÃ³n
  geolocator: ^14.0.2
  location: ^8.0.1
  
  # Almacenamiento local
  shared_preferences: ^2.2.2
  
  # Firebase - Servicios en la nube
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  
  # Utilidades
  json_annotation: ^4.8.1
  vibration: ^3.1.4
  flutter_tts: ^4.0.2
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.2
  flutter_foreground_task: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true